Relay.Authorization/Relay.Authorization.Web/Controllers/RegistrationController.cs
using System.Web.Mvc;
using MomentumPlus.Relay.Authorization.Services;
using MomentumPlus.Relay.Authorization.Services.Registration;
using MomentumPlus.Relay.Authorization.Helpers;
using MomentumPlus.Relay.Authorization.Models;
using System.Threading.Tasks;
using System;
using System.Web.Configuration;

namespace MomentumPlus.Relay.Authorization.Controllers
{
    public class RegistrationController : BaseController
    {
        /// <summary>
        /// Render Sign Up Page
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Summary");
            }

            return View("~/Views/Registration/Registration.cshtml");
        }



        [HttpPost]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public async Task<ActionResult> SignUp(RegistrationViewModel model)
        {
            if (ModelState.IsValid)
            {
                RegistrationMediator mediator = new RegistrationMediator();

                RegistrationStep validateExpDateStep = new ValidateExpDateRegistrationStep(mediator);
                RegistrationStep paymentStep = new PaymentRegistrationStep(mediator);
                RegistrationStep registrationUserStep = new IdentityUserRegistrationStep(mediator);
                RegistrationStep subscriptionCreationStep = new SubscriptionCreationRegistrationStep(mediator);
                RegistrationStep initializeRelayStep = new InitializeRelayRegistrationStep(mediator);

                mediator.ValidateExpDateStep = validateExpDateStep;
                mediator.PaymentStep = paymentStep;
                mediator.RegistrationUserStep = registrationUserStep;
                mediator.SubscriptionCreationStep = subscriptionCreationStep;
                mediator.InitializeRelayRegistrationStep = initializeRelayStep;

                validateExpDateStep.Execute(model, ModelState);
                paymentStep.Execute(model, ModelState);
                registrationUserStep.Execute(model, ModelState);
                subscriptionCreationStep.Execute(model, ModelState);
                initializeRelayStep.Execute(model, ModelState);

                var errorsMessage = ModelState.ErrorsMessage();

                if (!Boolean.Parse(WebConfigurationManager.AppSettings["isInTestMode"]) && errorsMessage == null)
                {
                    var token = await UserManager.GenerateEmailConfirmationTokenAsync(mediator.CreatedUser.Id);
                    var callbackUrl = Url.Action("RegisterConfirmation", "Account", new { userId = mediator.CreatedUser.Id, token = token }, protocol: Request.Url.Scheme);

                    await SignInManager.UserManager.SendEmailAsync(mediator.CreatedUser.Id, "Thank you for purchasing RelayWorks",
                    " Hello, " + model.Name + "! <br />" +
                    " Thank you for purchasing RelayWorks. <br />" +
                    " To activate you account, please follow this <a href=\"" + callbackUrl + "\">link</a>" +
                    " <br /> Kind Regards, <br /> " +
                    " RelayWorks Team");
                }

                if (ModelState.IsValid)
                {
                    return RedirectToAction("InitializeRelay", "Home");
                }
            }

            return Json(new { status = false, data = new { message = ModelState.ErrorsMessage(), errors = ModelState.Errors() } }, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// Price Constants
        /// </summary>
        [HttpPost]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult PriceConstants()
        {
            var model = SubscriptionService.GetPricesConstants();

            return Json(model);
        }



        /// <summary>
        /// Sign Up Step 1
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Step1()
        {
            return PartialView("~/Views/Registration/_Step_1.cshtml");
        }

        /// <summary>
        /// Sign Up Step 2
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Step2()
        {
            return PartialView("~/Views/Registration/_Step_2.cshtml");
        }


        /// <summary>
        /// Sign Up Step 3
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Step3()
        {
            return PartialView("~/Views/Registration/_Step_3.cshtml");
        }


        /// <summary>
        /// Sign Up Step 4
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Step4()
        {
            return PartialView("~/Views/Registration/_Step_4.cshtml");
        }
    }
}

Relay.Authorization/Relay.Authorization.Web/Views/Main.cshtml
@model LoginViewModel

@{
    Layout = "~/Views/Shared/AuthLayout.cshtml";
    ViewBag.Title = "RelayWorks™ | iHandover";
}


<div class="main-page">
    <div class="wrapper">

        <div class="relay-logo-block">
            <div class="row">
                <div class="col-xs-6">
                    <a class="logo" href="\"></a>
                </div>
                <div class="col-xs-6 text-right header-buttons">
                    <a class="btn btn-login" href="@Url.Action("Login")">Login</a>
                </div>
            </div>
        </div>

        <div class="content-area">

            <div Id="welcome-carousel" class="carousel slide" data-ride="slide">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#welcome-carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#welcome-carousel" data-slide-to="1" class="disabled"></li>
                    <li data-target="#welcome-carousel" data-slide-to="2" class="disabled"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="row">
                    <div class="col-xs-12">
                        <div class="carousel-inner">
                            <div class="item active">
                                <div class="carousel-content">
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="welcome">
                                                Welcome
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-xs-12 text-center" style="padding-top: 18vh">
                                                <a class="btn btn-purchase" href="@Url.Action("Index", "Registration")">
                                                    Purchase
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="carousel-content">
                                    <div class="row">
                                        <div class="col-xs-12">

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="carousel-content">
                                    <div class="row">
                                        <div class="col-xs-12">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


            </div>

            <div class="clearfix"></div>
        </div>
        <div class="footer">
            <div class="footer-block">
                <div class="row">
                    <div class="col-xs-6 no-padding">
                        <div class="row padding-top-20">
                            <div class="col-xs-12 no-padding">

                                <div class="ihandover-logo" onclick="window.open('http://relayworks.io', '_blank');"></div>
                            </div>
                            <div class="col-xs-12 no-padding">
                                <div class="current-year padding-top-10">
                                    © @DateTime.Now.Year
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 no-padding">
                        <div class="social-buttons">
                            <a class="btn btn-twitter" href="https://twitter.com/ihandover" target="_blank">
                            </a>
                            <a class="btn btn-linkedin" href="https://www.linkedin.com/company/2378457" target="_blank">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>