Relay.Authorization/Relay.Authorization.Web/Controllers/AdminDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MomentumPlus.Core.Models;
using MomentumPlus.Relay.Helpers;
using MomentumPlus.Relay.Models;

namespace MomentumPlus.Relay.Authorization.Controllers
{
    public class AdminDashboardController : BaseController
    {
        /// <summary>
        /// Render Admin Dashboard Page
        /// </summary>
        public ActionResult Index()
        {
            var model = SubscriptionService.GetAllSubscriptions();

            return View("~/Views/AdminDashboard/Dashboard.cshtml", model);
        }


        /// <summary>
        /// Go To Relay
        /// </summary>
        public ActionResult GoToRelay(Guid subscriptionId)
        {
           AppSession.Current.CurrentSubscriptionId = subscriptionId;

            return RedirectToAction("Index", "MyTeam");
        }

        /// <summary>
        /// Extend Trial
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ExtendTrial(Guid subscriptionId)
        {
            SubscriptionService.ExtendTrial(subscriptionId);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Extend Trial
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StartNewTrial(Guid subscriptionId)
        {
            SubscriptionService.StartTrial(subscriptionId);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteSubscription(Guid subscriptionId)
        {
            SubscriptionService.DeleteSubscriptionAndUsers(subscriptionId);

            return RedirectToAction("Index");
        }

        public ActionResult ChangeSubscriptionPeriod(Guid subscriptionId)
        {
            return RedirectToAction("SetNewSubscriptionPeriod", "Settings", new { subscriptionId  = subscriptionId });
        }
    }
}

Relay.Authorization/Relay.Authorization.Web/Controllers/TrialController.cs
using MomentumPlus.Relay.Authorization.Helpers;
using MomentumPlus.Relay.Authorization.Models;
using MomentumPlus.Relay.Authorization.Services;
using MomentumPlus.Relay.Authorization.Services.Registration;
using System.Threading.Tasks;
using System.Web.Mvc;
using MomentumPlus.Relay.Models;
using System;
using System.Web.Configuration;

namespace MomentumPlus.Relay.Authorization.Controllers
{
    public class TrialController :  BaseController
    {

        public ActionResult TrialRegistration()
        {
            return View("~/Views/Trial/RegistrationTrial.cshtml");
        }

        [HttpPost]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public async Task<ActionResult> SignUp(RegistrationTrialViewModel model)
        {
            if (ModelState.IsValid)
            {
                RegistrationMediator mediator = new RegistrationMediator();

                RegistrationStep registrationUserStep = new IdentityUserRegistrationStep(mediator);
                RegistrationStep subscriptionCreationStep = new SubscriptionCreationRegistrationStep(mediator);
                RegistrationStep initializeRelayStep = new InitializeRelayRegistrationStep(mediator);

                mediator.RegistrationUserStep = registrationUserStep;
                mediator.SubscriptionCreationStep = subscriptionCreationStep;
                mediator.InitializeRelayRegistrationStep = initializeRelayStep;

                registrationUserStep.Execute(model, ModelState);
                subscriptionCreationStep.Execute(model, ModelState);
                initializeRelayStep.Execute(model, ModelState);

                if (!Boolean.Parse(WebConfigurationManager.AppSettings["isInTestMode"]))
                {
                    var token = await UserManager.GenerateEmailConfirmationTokenAsync(mediator.CreatedUser.Id);
                    var callbackUrl = Url.Action("RegisterConfirmation", "Account", new { userId = mediator.CreatedUser.Id, token = token }, protocol: Request.Url.Scheme);

                    await SignInManager.UserManager.SendEmailAsync(mediator.CreatedUser.Id, "Thank you for purchasing RelayWorks",
                    " Hello, " + model.Name + "! <br />" +
                    " Thank you for purchasing RelayWorks. <br />" +
                    " To activate you account, please follow this <a href=\"" + callbackUrl + "\">link</a>" +
                    " <br /> Kind Regards, <br /> " +
                    " RelayWorks Team");
                }

                if (ModelState.IsValid)
                {
                    return RedirectToAction("InitializeRelay", "Home");
                }
            }

            return Json(new { status = false, data = new { message = ModelState.ErrorsMessage(), errors = ModelState.Errors() } }, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// Price Constants
        /// </summary>
        [HttpPost]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult PriceConstants()
        {
            var model = SubscriptionService.GetPricesConstants();

            return Json(model);
        }



        /// <summary>
        /// Trial Step 1
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Step1()
        {
            return PartialView("~/Views/Trial/_Step_1.cshtml");
        }

        /// <summary>
        /// Trial Step 2
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Step2()
        {
            return PartialView("~/Views/Trial/_Step_2.cshtml");
        }


        /// <summary>
        /// Trial Step 3
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Step3()
        {
            return PartialView("~/Views/Trial/_Step_3.cshtml");
        }

        /// <summary>
        /// Sign Up Step 4
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Step4()
        {
            return PartialView("~/Views/Trial/_Step_4.cshtml");
        }


        /// <summary>
        /// Go to login
        /// </summary>
        [HttpGet]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult Login()
        {
            return RedirectToAction("Index", "AdminDashboard");
        }


        [HttpPost]
        [AllowAnonymous]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult PayForTrial(UpgradeSubscriptionViewModel model)
        {
            if (ModelState.IsValid)
            {
                RegistrationMediator mediator = new RegistrationMediator();

                RegistrationStep validateExpDateStep = new ValidateExpDateRegistrationStep(mediator);
                RegistrationStep paymentStep = new PaymentRegistrationStep(mediator);
                RegistrationStep subscriptionStep = new SubscriptionCreationRegistrationStep(mediator);

                mediator.ValidateExpDateStep = validateExpDateStep;
                mediator.PaymentStep = paymentStep;
                mediator.SubscriptionCreationStep = subscriptionStep;

                validateExpDateStep.Execute(model, ModelState);
                paymentStep.Execute(model, ModelState);
                subscriptionStep.Execute(model, ModelState);

                if (ModelState.IsValid)
                {

                    return Json(new { status = true, data = new { message = "Upgrade Success" } }, JsonRequestBehavior.AllowGet);
                }

            }

            return Json(new { status = false, data = new { message = ModelState.ErrorsMessage(), errors = ModelState.Errors() } }, JsonRequestBehavior.AllowGet);
        }
    }
}

Relay.Authorization/Relay.Authorization.Web/Views/AdminDashboard/Dashboard.cshtml
@using MomentumPlus.Relay.Extensions
@model IEnumerable<SubscriptionViewModel>
@{
    Layout = "~/Views/Shared/AuthLayout.cshtml";
    ViewBag.Title = "RelayWorks™ | iHandover Admin Dashboard";
}

<div class="dashboard-page">
  <div class="wrapper">

    <div class="relay-logo-block">
      <div class="row header-buttons">
        <div class="col-xs-4">
          <a class="logo" href="@Url.Action("Index", "AdminDashboard")"></a>
        </div>
        <div class="col-xs-8 text-right">
            @*<a class="btn btn-menu" href="@Url.Action("GlobalTemplates", "Templates")" style="width: 130px !important;">Global Templates</a>*@
            <a class="btn btn-menu" href="@Url.Action("TrialRegistration", "Trial")">New trial</a>
            <a class="btn btn-menu active" href="@Url.Action("Index", "AdminDashboard")">Dashboard</a>
            <a class="btn btn-logout" href="@Url.Action("LogOff", "Account")">Logout</a>
        </div>
      </div>
    </div>

    <div class="content-area">
      <h2>Active Subscriptions</h2>
      <div class="table-responsive">
        @if (Model != null && Model.Any())
        {
        <table class="table">
          <thead>
            <tr>
              <th>Manager Email</th>
              @*<th>Subscription Type</th>*@
              <th>Restriction Type</th>
              <th># Users</th>
              <th>Subscription Status</th>
              @*<th>Billing Period</th>*@
              <th>Created Date</th>
              <th>End Date</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @foreach (var subscription in Model)
            {
              <tr>
                <th>@subscription.ManagerEmail</th>
                @*<th>@subscription.SubscriptionType</th>*@
                <th>@subscription.RestrictionType</th>
                <th>@subscription.Users</th>
                <th>@subscription.SubscriptionStatus.GetEnumDescription()</th>
                @*<th>@subscription.BillingPeriod</th>*@
                <th>@subscription.CreatedDate</th>
                <th>@subscription.EndDate</th>
                <th>
                    @using (Html.BeginForm("ChangeSubscriptionPeriod", "AdminDashboard", FormMethod.Get))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("subscriptionId", @subscription.SubscriptionId)
                    <button type="submit" class="btn btn-start-trial" style="margin-bottom: 5px !important;">Change Period & Status</button>
                    }
                </th>
                <th><a class="glyphicon glyphicon-eye-open" href="@Url.Action("GoToRelay", "AdminDashboard", new {subscriptionId = subscription.SubscriptionId})"></a></th>
                <th>
                  @if (@subscription.SubscriptionStatus == StatusOfSubscription.TrialEnd)
                  {
                    using (Html.BeginForm("StartNewTrial", "AdminDashboard", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("subscriptionId", @subscription.SubscriptionId)
                        <button type="submit" class="btn btn-start-trial">Start New Trial Period</button>
                    }
                  }
                  @if (@subscription.SubscriptionStatus == StatusOfSubscription.Trialing)
                  {
                    using (Html.BeginForm("ExtendTrial", "AdminDashboard", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("subscriptionId", @subscription.SubscriptionId)
                        <button type="submit" class="btn btn-start-trial">Extend Trial</button>
                    }
                  }
                </th>
                <th>
                  @if (subscription.SubscriptionStatus == StatusOfSubscription.Active && subscription.EndDateTime.HasValue && subscription.EndDateTime > DateTime.UtcNow)
                  {

                  }
                  else
                  {
                    using (Html.BeginForm("DeleteSubscription", "AdminDashboard", FormMethod.Post))
                    {
                      @Html.AntiForgeryToken()
                      @Html.Hidden("subscriptionId", @subscription.SubscriptionId)
                      <button type="submit" class="btn btn-delete-subscription" onclick="javascript: return deleteSubscription();">Delete Subscription</button>
                    }
                  }

                </th>

              </tr>
            }
          </tbody>

        </table>
        }
        else
        {
        <div class="table-block">
          <div class="text-center message-block">
            No subscriptions are available.
          </div>
        </div>
        }
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="footer">
      <div class="footer-block">
        <div class="row">
          <div class="col-xs-6 no-padding">
            <div class="row padding-top-20">
              <div class="col-xs-12 no-padding">

                <div class="ihandover-logo" onclick="window.open('http://relayworks.io', '_blank');"></div>
              </div>
              <div class="col-xs-12 no-padding">
                <div class="current-year padding-top-10">
                  © @DateTime.Now.Year
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-6 no-padding">
            <div class="social-buttons">
              <a class="btn btn-twitter" href="https://twitter.com/ihandover" target="_blank">
              </a>
              <a class="btn btn-linkedin" href="https://www.linkedin.com/company/2378457" target="_blank">
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>

    location.reload(true);

    function deleteSubscription() {
        var r = confirm("Are you sure you want delete this Subscription?");
        if (r == false) {
            return false;
        }
    }
</script>